[package]
name = "tyu"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tyu"
path = "src/main.rs"

[dependencies]
codegen-core = { path = "../codegen-core" }
frontend = { path = "../frontend" }
harness-core = { path = "../harness-core" }
hex = "0.4"
libc = "0.2"
lmod = { path = "../lmod" }

[dev-dependencies]
hex = "0.4"
hosted = { path = "../hosted" }
libc = "0.2"
loader-core = { path = "../loader-core" }
