[package]
name = "lmod-encrypt"
version = "0.1.0"
edition = "2021"

[lib]
name = "lmod_encrypt"
path = "src/lib.rs"

[[bin]]
name = "lmod-encrypt"
path = "src/main.rs"

[dependencies]
lmod = { path = "../lmod" }
chacha20poly1305 = "0.10"
getrandom = "0.2"
hex = "0.4"
rand_core = { version = "0.6", features = ["std"] }

[dev-dependencies]
hmac = "0.12"
sha2 = "0.10"
