use ir as lir;

use crate::ophelpers;
use crate::util::write_u32;
use crate::X86_64HostedBackend;

pub fn emit_region_create(gen: &mut X86_64HostedBackend<'_>) {
    let scan_loop = gen.fresh_label();
    let found_free = gen.fresh_label();
    let size_ok = gen.fresh_label();
    let mmap_ok = gen.fresh_label();
    gen.out.write(b"  sub r15, 8\n");
    gen.out.write(b"  mov rsi, [r15]\n"); // size
    gen.out.write(b"  cmp rsi, 0\n");
    gen.out.write(b"  jne .region_size_ok_");
    write_u32(gen.out, size_ok);
    gen.out.write(b"\n");
    gen.out.write(b"  mov rdi, ");
    write_u32(gen.out, lir::trap_code_u32(lir::TrapCode::Unreachable));
    gen.out.write(b"\n");
    gen.out.write(b"  jmp __lang_trap\n");
    gen.out.write(b".region_size_ok_");
    write_u32(gen.out, size_ok);
    gen.out.write(b":\n");
    // Scan slots 0..15 for a free (destroyed) slot where size == 0.
    gen.out.write(b"  xor rcx, rcx\n");
    gen.out.write(b".region_scan_");
    write_u32(gen.out, scan_loop);
    gen.out.write(b":\n");
    gen.out.write(b"  cmp rcx, 16\n");
    gen.out.write(b"  jae .region_alloc_new_");
    write_u32(gen.out, scan_loop);
    gen.out.write(b"\n");
    gen.out.write(b"  cmp qword [__region_size + rcx*8], 0\n");
    gen.out.write(b"  je .region_found_free_");
    write_u32(gen.out, found_free);
    gen.out.write(b"\n");
    gen.out.write(b"  inc rcx\n");
    gen.out.write(b"  jmp .region_scan_");
    write_u32(gen.out, scan_loop);
    gen.out.write(b"\n");
    gen.out.write(b".region_found_free_");
    write_u32(gen.out, found_free);
    gen.out.write(b":\n");
    gen.out.write(b"  jmp .region_setup_");
    write_u32(gen.out, scan_loop);
    gen.out.write(b"\n");
    // No free slot found; use __region_next if under 16.
    gen.out.write(b".region_alloc_new_");
    write_u32(gen.out, scan_loop);
    gen.out.write(b":\n");
    gen.out.write(b"  mov rcx, [__region_next]\n");
    gen.out.write(b"  cmp rcx, 16\n");
    gen.out.write(b"  jb .region_setup_");
    write_u32(gen.out, scan_loop);
    gen.out.write(b"\n");
    gen.out.write(b"  mov rdi, ");
    write_u32(gen.out, lir::trap_code_u32(lir::TrapCode::Unreachable));
    gen.out.write(b"\n");
    gen.out.write(b"  jmp __lang_trap\n");
    gen.out.write(b".region_setup_");
    write_u32(gen.out, scan_loop);
    gen.out.write(b":\n");
    // If we used the next-new path, increment __region_next.
    gen.out.write(b"  mov rax, rcx\n");
    gen.out.write(b"  inc rax\n");
    gen.out.write(b"  cmp rax, [__region_next]\n");
    gen.out.write(b"  jbe .region_skip_inc_");
    write_u32(gen.out, scan_loop);
    gen.out.write(b"\n");
    gen.out.write(b"  mov [__region_next], rax\n");
    gen.out.write(b".region_skip_inc_");
    write_u32(gen.out, scan_loop);
    gen.out.write(b":\n");
    gen.out.write(b"  mov rax, rsi\n");
    gen.out.write(b"  add rax, 7\n");
    gen.out.write(b"  and rax, -8\n");
    gen.out.write(b"  mov rsi, rax\n");
    gen.out.write(b"  xor rdi, rdi\n");
    gen.out.write(b"  mov rdx, 3\n");
    gen.out.write(b"  mov r10, 0x22\n");
    gen.out.write(b"  mov r8, -1\n");
    gen.out.write(b"  xor r9, r9\n");
    gen.out.write(b"  mov rax, 9\n");
    gen.out.write(b"  syscall\n");
    gen.out.write(b"  test rax, rax\n");
    gen.out.write(b"  jns .region_mmap_ok_");
    write_u32(gen.out, mmap_ok);
    gen.out.write(b"\n");
    gen.out.write(b"  mov rdi, ");
    write_u32(gen.out, lir::trap_code_u32(lir::TrapCode::Unreachable));
    gen.out.write(b"\n");
    gen.out.write(b"  jmp __lang_trap\n");
    gen.out.write(b".region_mmap_ok_");
    write_u32(gen.out, mmap_ok);
    gen.out.write(b":\n");
    gen.out.write(b"  mov [__region_base + rcx*8], rax\n");
    gen.out.write(b"  mov [__region_size + rcx*8], rsi\n");
    gen.out.write(b"  mov qword [__region_off + rcx*8], 0\n");
    gen.out.write(b"  mov rax, rcx\n");
    ophelpers::emit_push_rax(gen.out);
}

pub fn emit_region_alloc(gen: &mut X86_64HostedBackend<'_>) {
    let ok = gen.fresh_label();
    let size_ok = gen.fresh_label();
    let live_ok = gen.fresh_label();
    let space_ok = gen.fresh_label();
    gen.out.write(b"  sub r15, 8\n");
    gen.out.write(b"  mov rdx, [r15]\n"); // size
    gen.out.write(b"  sub r15, 8\n");
    gen.out.write(b"  mov rax, [r15]\n"); // region handle
    gen.out.write(b"  cmp rax, 16\n");
    gen.out.write(b"  jb .region_alloc_ok_");
    write_u32(gen.out, ok);
    gen.out.write(b"\n");
    gen.out.write(b"  mov rdi, ");
    write_u32(gen.out, lir::trap_code_u32(lir::TrapCode::Unreachable));
    gen.out.write(b"\n");
    gen.out.write(b"  jmp __lang_trap\n");
    gen.out.write(b".region_alloc_ok_");
    write_u32(gen.out, ok);
    gen.out.write(b":\n");
    gen.out.write(b"  cmp rdx, 0\n");
    gen.out.write(b"  jne .region_alloc_size_ok_");
    write_u32(gen.out, size_ok);
    gen.out.write(b"\n");
    gen.out.write(b"  mov rdi, ");
    write_u32(gen.out, lir::trap_code_u32(lir::TrapCode::Unreachable));
    gen.out.write(b"\n");
    gen.out.write(b"  jmp __lang_trap\n");
    gen.out.write(b".region_alloc_size_ok_");
    write_u32(gen.out, size_ok);
    gen.out.write(b":\n");
    gen.out.write(b"  mov rcx, [__region_size + rax*8]\n");
    gen.out.write(b"  cmp rcx, 0\n");
    gen.out.write(b"  jne .region_alloc_live_");
    write_u32(gen.out, live_ok);
    gen.out.write(b"\n");
    gen.out.write(b"  mov rdi, ");
    write_u32(gen.out, lir::trap_code_u32(lir::TrapCode::Unreachable));
    gen.out.write(b"\n");
    gen.out.write(b"  jmp __lang_trap\n");
    gen.out.write(b".region_alloc_live_");
    write_u32(gen.out, live_ok);
    gen.out.write(b":\n");
    gen.out.write(b"  mov r8, [__region_off + rax*8]\n");
    gen.out.write(b"  add rdx, 7\n");
    gen.out.write(b"  and rdx, -8\n");
    gen.out.write(b"  mov r9, r8\n");
    gen.out.write(b"  add r9, rdx\n");
    gen.out.write(b"  cmp r9, rcx\n");
    gen.out.write(b"  jbe .region_alloc_space_");
    write_u32(gen.out, space_ok);
    gen.out.write(b"\n");
    gen.out.write(b"  mov rdi, ");
    write_u32(gen.out, lir::trap_code_u32(lir::TrapCode::Unreachable));
    gen.out.write(b"\n");
    gen.out.write(b"  jmp __lang_trap\n");
    gen.out.write(b".region_alloc_space_");
    write_u32(gen.out, space_ok);
    gen.out.write(b":\n");
    gen.out.write(b"  mov [__region_off + rax*8], r9\n");
    gen.out.write(b"  mov rcx, [__region_base + rax*8]\n");
    gen.out.write(b"  add rcx, r8\n");
    gen.out.write(b"  mov rax, rcx\n");
    ophelpers::emit_push_rax(gen.out);
}

pub fn emit_region_reset(gen: &mut X86_64HostedBackend<'_>) {
    let ok = gen.fresh_label();
    let live = gen.fresh_label();
    gen.out.write(b"  sub r15, 8\n");
    gen.out.write(b"  mov rax, [r15]\n");
    gen.out.write(b"  cmp rax, 16\n");
    gen.out.write(b"  jb .region_reset_ok_");
    write_u32(gen.out, ok);
    gen.out.write(b"\n");
    gen.out.write(b"  mov rdi, ");
    write_u32(gen.out, lir::trap_code_u32(lir::TrapCode::Unreachable));
    gen.out.write(b"\n");
    gen.out.write(b"  jmp __lang_trap\n");
    gen.out.write(b".region_reset_ok_");
    write_u32(gen.out, ok);
    gen.out.write(b":\n");
    gen.out.write(b"  mov rcx, [__region_size + rax*8]\n");
    gen.out.write(b"  cmp rcx, 0\n");
    gen.out.write(b"  jne .region_reset_live_");
    write_u32(gen.out, live);
    gen.out.write(b"\n");
    gen.out.write(b"  mov rdi, ");
    write_u32(gen.out, lir::trap_code_u32(lir::TrapCode::Unreachable));
    gen.out.write(b"\n");
    gen.out.write(b"  jmp __lang_trap\n");
    gen.out.write(b".region_reset_live_");
    write_u32(gen.out, live);
    gen.out.write(b":\n");
    gen.out.write(b"  mov qword [__region_off + rax*8], 0\n");
}

pub fn emit_region_destroy(gen: &mut X86_64HostedBackend<'_>) {
    let ok = gen.fresh_label();
    let live = gen.fresh_label();
    let munmap_ok = gen.fresh_label();
    gen.out.write(b"  sub r15, 8\n");
    gen.out.write(b"  mov rax, [r15]\n");
    gen.out.write(b"  mov r11, rax\n");
    gen.out.write(b"  cmp rax, 16\n");
    gen.out.write(b"  jb .region_destroy_ok_");
    write_u32(gen.out, ok);
    gen.out.write(b"\n");
    gen.out.write(b"  mov rdi, ");
    write_u32(gen.out, lir::trap_code_u32(lir::TrapCode::Unreachable));
    gen.out.write(b"\n");
    gen.out.write(b"  jmp __lang_trap\n");
    gen.out.write(b".region_destroy_ok_");
    write_u32(gen.out, ok);
    gen.out.write(b":\n");
    gen.out.write(b"  mov rcx, [__region_size + r11*8]\n");
    gen.out.write(b"  cmp rcx, 0\n");
    gen.out.write(b"  jne .region_destroy_live_");
    write_u32(gen.out, live);
    gen.out.write(b"\n");
    gen.out.write(b"  mov rdi, ");
    write_u32(gen.out, lir::trap_code_u32(lir::TrapCode::Unreachable));
    gen.out.write(b"\n");
    gen.out.write(b"  jmp __lang_trap\n");
    gen.out.write(b".region_destroy_live_");
    write_u32(gen.out, live);
    gen.out.write(b":\n");
    gen.out.write(b"  mov rdi, [__region_base + r11*8]\n");
    gen.out.write(b"  mov rsi, rcx\n");
    gen.out.write(b"  mov rax, 11\n");
    gen.out.write(b"  syscall\n");
    gen.out.write(b"  test rax, rax\n");
    gen.out.write(b"  jns .region_destroy_munmap_ok_");
    write_u32(gen.out, munmap_ok);
    gen.out.write(b"\n");
    gen.out.write(b"  mov rdi, ");
    write_u32(gen.out, lir::trap_code_u32(lir::TrapCode::Unreachable));
    gen.out.write(b"\n");
    gen.out.write(b"  jmp __lang_trap\n");
    gen.out.write(b".region_destroy_munmap_ok_");
    write_u32(gen.out, munmap_ok);
    gen.out.write(b":\n");
    gen.out.write(b"  mov qword [__region_base + r11*8], 0\n");
    gen.out.write(b"  mov qword [__region_size + r11*8], 0\n");
    gen.out.write(b"  mov qword [__region_off + r11*8], 0\n");
}
