import Tyu.Gen.Render
import Tyu.Gen.Sha256
import Tyu.Conformance.Runner
import Tyu.Conformance.Cfg
import Tyu.Conformance.VectorRun

/-! The re-derivation engine (PLAN-VERIFY-3 P14.2, §Q12).

The `rederive` method (`trust: proof, method: rederive`): the port re-runs
the abstract interpreter `Tyu.Abs` over a word's IR and re-derives the
obligation discharges the in-tree engine would make — then upgrades the
`checked`-class interval discharges to `proof` (which is what `proven`
requires of the automation layer, §Q12). T-A/T-B (`Tyu.Sound.TA`/`TB`) are
this engine's soundness; the conformance corpus pins its execution.

Two modes:

  - `--corpus <dir>` — the shared differential pin: every `tyu.vec/1`
    program-shaped document generated by `verifier::gen` +
    `verifier::discharge` (the Rust in-tree engine) is re-executed by THIS
    engine and must reproduce the committed expectations (tri + interval)
    byte-for-byte. Zero divergence = the port and the in-tree engine agree
    on every obligation, including the trust class.
  - `--obl <artifacts> --out <verdicts>` — the product path: re-derive a
    `tyu.obl/v2` artifact's obligations (subtype-range cast sites and
    top-of-stack returns) into `tyu.verdicts/v2` records with
    `trust: proof, method: rederive` + the statement binding. Soundness of
    every discharge: the entry sig is inferred conservatively (over-open for
    input-dependent casts — never a wrong discharge; exact where the word is
    input-free or the value is input-independent). -/

namespace Tyu.Rederive

open Tyu.Conformance
open Tyu.Gen.Render

def renderErrMsg (e : Tyu.Gen.Render.RenderErr) : String :=
  match e with
  | .notOblDoc m => m
  | .unknownForm m => m


/-- The subtype range the corpus casts use (`percent`, mirrors
`Tyu.Abs.percentRange`). -/
def subtypeRange (o : Obl) : Option (Int × Int) :=
  match o.formulaOp with
  | "InRange" => some (o.lo, o.hi)
  | _ => none

/-- The artifact's declared subtype names (from `facts.subtypes[].name`). A
real lowering emits `cast <TypeName>` (e.g. `cast Percent`), which the raw
corpus parser only flags for the lowercase `cast percent` synthetic word —
the re-derivation recognizes any cast whose target is a declared subtype. -/
def subtypeNamesOf (doc : String) : List String :=
  match parseJson doc with
  | none => []
  | some j =>
      let subs := ((j.field "facts").bind (fun f => (f.field "subtypes").bind Json.asArr)) |>.getD []
      subs.filterMap (fun s => (s.field "name").bind Json.asStr)

/-- A subtype-aware cast parser: the synthetic `cast percent` (corpus) and
the real `cast <TypeName>` (langc lowering) both flag `subtypeCast`. -/
def castTargetOf (line : String) : Option String :=
  let toks := (splitOnStr ' ' (trim line)).filter (fun t => t ≠ "")
  match toks with
  | "cast" :: [ty] => some ty
  | _ => none

namespace BlockSuccs

-- Successor routing (mirrors `Tyu.Conformance.parseBlocks`' local).
def of (ops : List OpInst) : List Nat :=
  match ops.getLast? with
  | some o => (match o.form, o.brTgt, o.brIfTgts with
      | .br, some t, _ => [t]
      | .br_if, _, some (t, e) => [t, e]
      | _, _, _ => [])
  | none => []

end BlockSuccs

def parseBlocksSub (subs : List String) (text : String) : List Block :=
  let lines := splitOnStr '\n' text
  let (acc, curId, curOps) := lines.foldl
    (fun (acc : List Block × Option Nat × List OpInst) line =>
      let (blks, cid, cops) := acc
      let t := trim line
      if t == "" then acc
      else if t.startsWith "block b" then
        match dropPrefixStr "block b" t with
        | some rest =>
            match parseNat rest with
            | some i =>
                let blksFinal := match cid with
                  | some id => (Block.mk id cops.reverse (BlockSuccs.of cops.reverse)) :: blks
                  | none => blks
                (blksFinal, some i, [])
            | none => acc
        | none => acc
      else match parseOp t with
        | some o =>
            let o' := match castTargetOf t with
              | some ty => if subs.any (fun s => s == ty) then o.setSubtypeCast true else o
              | none => o
            (blks, cid, o' :: cops)
        | none => acc)
    ([], none, [])
  let final := match curId with
    | some id => (Block.mk id curOps.reverse (BlockSuccs.of curOps.reverse)) :: acc
    | none => acc
  final.reverse



/-- Run a word's block list from a callee-entry state and return the per-block
pre-cast intervals of narrowing casts (CFG order — mirrors
`verifier::interp::discharge_word`'s `seen_casts`). -/
def castPresOf (blocks : List Block) (states : List State) (sr : Option (Int × Int))
    (wb : Nat) (mem : MemModel) : List Interval :=
  let (pres, _, _) := blocks.foldl
    (fun (acc : List Interval × MemModel × State) b =>
      let (pre, m, _) := acc
      -- start from the block's fixpoint entry state
      let st0 := states.getD b.id (State.fresh 64)
      let (pre', m', _) := b.ops.foldl
        (fun (acc2 : List Interval × MemModel × State) o =>
          let (p2, m2, s2) := acc2
          let preNow := if o.form == Tyu.IR.OpForm.cast && o.subtypeCast then some s2.topInterval
                        else none
          let (m3, s3) := stepOp o s2 sr wb m2
          (match preNow with | some iv => p2 ++ [iv] | none => p2, m3, s3))
        (pre, m, st0)
      (pre', m', st0))
    ([], mem, State.fresh 64)
  pres

/-- Infer the word's signature from its obligations: `sig_in` is one past the
largest `in.i` reference (0 when none), `sig_out` one past the largest
`out.i` reference (1 when none). Conservative: input-carrying words with no
`in.i` obligation run with an empty entry stack, which over-opens
(input-dependent casts stay `⊤` — a missed discharge, never a wrong one). -/
def inferSig (ids : List Obl) : Nat × Nat :=
  let sin := ids.foldl (fun acc o =>
    match Tyu.Gen.Render.oelRoot o.oel with
    | some (n, i) => if n == "in" then max acc (i + 1) else acc
    | none => acc) 0
  let sout := ids.foldl (fun acc o =>
    match Tyu.Gen.Render.oelRoot o.oel with
    | some (n, i) => if n == "out" then max acc (i + 1) else acc
    | none => acc) 0
  (sin, if sout == 0 then 1 else sout)

/-- One re-derived verdict decision for an obligation. -/
structure Decision where
  discharged : Bool
  interval : Interval
  reason : String
  deriving Repr

/-- Re-derive one obligation of a word. `casts` are the word's pre-cast
intervals (CFG order); `exit` is the fold of the ret-blocks. -/
def dischargeObl (o : Obl) (casts : List Interval) (exit : State) : Decision :=
  match o.formulaOp with
  | "InRange" =>
      let iv : Interval := match o.oel with
        | .opaqueMk => Interval.top
        | .inVar _ => Interval.top  -- callee inputs are `⊤` (unproven)
        | .outVar _ => exit.topInterval
        | .castArg _ _ _ => casts.getD o.occurrence Interval.top
      match evalInRange iv o.lo o.hi with
      | Tri.defTrue => Decision.mk true iv ""
      | Tri.defFalse => Decision.mk false iv "provably-failing"
      | Tri.top => Decision.mk false iv ("interval top " ++ toText iv ++ " vs [" ++ toString o.lo ++ ", " ++ toString o.hi ++ "]")
  | _ => Decision.mk false Interval.top "not-rederivable"

/-- The `Ctx` for statement binding (mirrors `GenMain`'s per-obligation ctx). -/
def ctxOf (a : Artifact) (o : Obl) (ir : String) : Ctx :=
  { target := a.target, model := a.modelSemantics, module := a.module,
    word := o.word, wordIrHash := wordIrHash ir, kind := o.kind,
    occurrence := o.occurrence, refinement := none }

/-- `statement_hash` of an obligation (§6.2). -/
def hashOf (a : Artifact) (o : Obl) (ir : String) : String :=
  statementHash (ctxOf a o ir) o

/-- The certifier identity this port signs re-derivation productions with. -/
def certifier (toolchain : String) : String :=
  let tool := jobj [ ("name", jstr "rederive"), ("version", jstr "0.1.0") ]
  let c := jobj [ ("class", jstr "port"), ("name", jstr "lean"),
                  ("recognition", jstr "tyu-port/lean/1"),
                  ("tool", tool), ("toolchain", jstr toolchain) ]
  c

/-- One verdict record (a re-derived discharge: `trust: proof`,
`method: rederive`, `proof.kind: rederive`, T-B statement). -/
def recordOf (a : Artifact) (o : Obl) (dec : Decision) (ir : String) : String :=
  let proof := jobj [ ("kind", jstr "rederive"), ("statement", jstr "T-B") ]
  let base := jobj [ ("id", jstr o.id), ("id_hash", jstr o.idHash),
                     ("statement_hash", jstr (hashOf a o ir)),
                     ("proof", proof) ]
  if dec.discharged then
    jobj [ ("id", jstr o.id), ("id_hash", jstr o.idHash),
           ("status", jstr "discharged"), ("trust", jstr "proof"),
           ("method", jstr "rederive"), ("statement_hash", jstr (hashOf a o ir)),
           ("proof", proof) ]
  else
    let witness := jobj [ ("reason", jstr dec.reason) ]
    let note := jobj [ ("id", jstr o.id), ("id_hash", jstr o.idHash),
                       ("status", jstr "open"), ("trust", jstr "open"),
                       ("witness", witness) ]
    note

/-- Re-derive a whole `tyu.obl/v2` artifact into a `tyu.verdicts/v2` document. -/
def rederiveArtifact (doc : String) (toolchain : String) : Except String String :=
  match parseArtifact doc with
  | Except.error e => Except.error (renderErrMsg e)
  | Except.ok a =>
      let subs := subtypeNamesOf doc
      let records : List String := a.obligations.filterMap (fun o =>
        match a.words.find? (fun w => w.name == o.word) with
        | none => none
        | some wr =>
            match parseBlocksSub subs wr.ir with
            | [] => none
            | blocks =>
                let (sin, sout) := inferSig (a.obligations.filter (fun x => x.word == o.word))
                let (_, cf) := runCfg blocks sin sout (some (0, 100)) 64 MemModel.flat
                let exit := exitState blocks cf (some (0, 100)) 64 MemModel.flat
                let casts := castPresOf blocks cf (some (0, 100)) 64 MemModel.flat
                let dec := dischargeObl o casts exit
                some (recordOf a o dec wr.ir))
      let body := "{\"schema\":" ++ jstr "tyu.verdicts/v2"
        ++ ",\"certifier\":" ++ certifier toolchain
        ++ ",\"semantics\":" ++ jstr "tyu.ir-sem/1.0"
        ++ ",\"stmt\":" ++ jstr "tyu.stmt/1.0"
        ++ ",\"target\":" ++ jstr a.target
        ++ ",\"model_semantics\":" ++ jstr a.modelSemantics
        ++ ",\"verdicts\":[" ++ String.intercalate "," records ++ "]"
        ++ "}"
      Except.ok body

/-- The differential mode: re-run a `tyu.vec/1` program corpus with THIS
engine and return `(programs, mismatches)` (`runVecFile` is the absorbed
`Tyu.Abs` abstract transfer — exactly the engine T-A/T-B justify). -/
def runCorpus (content : String) : Except String (Nat × List Mismatch) :=
  match parseVecFile content with
  | none => Except.error "not a valid tyu.vec/1 document"
  | some f => Except.ok (f.vectors.length, runVecFile f)

end Tyu.Rederive