#!/usr/bin/env bash
# PLAN-VERIFY-3 P14.2 — the re-derivation differential gate (FR-13, §11.5).
#
# The port's `rederive` exe re-runs the abstract interpreter `Tyu.Abs` over
# ≥ 10^5 programs generated by `verifier::gen` and must agree with the
# in-tree engine EXACTLY — per program, the trust class (tri) AND the
# interval. This is the T-A/T-B mechanical pin: T-A proves the transfer
# sound, the differential proves the two engines compute it identically.
#
# Also drives the automation-only `proven` build (`proven_automation_only`):
# a module discharged entirely by `rederive` (no developer proofs) builds
# under `--verify-policy=proven` — §Q12's "port re-derivation upgrades the
# interval engine's discharges to proof without developer effort".
#
# Usage: bash ci/differential.sh [lean]
# Exit 0 on agreement; the wall-clock budget (NFR-3) is printed and enforced
# loosely (a multiplier of the last baseline; the differential itself must
# pass).

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PORT_DIR="$ROOT/verification/ports/lean"
N="${TYU_REDERIVE_N:-100000}"
BUDGET="${TYU_REDERIVE_BUDGET:-600}"

msg()  { local c=$1; shift; tput setaf "$c" 2>/dev/null || true; echo "  $*"; tput sgr0 2>/dev/null || true; }

msg 3 "  differential.sh: port expected (verification/ports/lean)"
if [ ! -f "$PORT_DIR/lakefile.toml" ] || [ ! -f "$PORT_DIR/lean-toolchain" ]; then
    msg 1 "  differential.sh: $PORT_DIR lacks lakefile.toml / lean-toolchain"
    exit 1
fi

# --- toolchain + port build -------------------------------------------------
msg 3 "  differential.sh: building the port (Tyu + rederive)"
( cd "$PORT_DIR" && lake build Tyu rederive ) || {
    msg 1 "  differential.sh: lake build Tyu rederive failed"
    exit 1
}
msg 2 "  differential.sh: port built; rederive exe present: $([ -x "$PORT_DIR/.lake/build/bin/rederive" ] && echo yes || echo NO)"

# --- the ≥10^5 differential ------------------------------------------------
msg 3 "  differential.sh: Rust re-derivation differential over ${N} programs (TYU_REDERIVE_E2E=1)"
START=$(date +%s)
( cd "$ROOT" && TYU_REDERIVE_E2E=1 TYU_REDERIVE_N="$N" \
    cargo test -q -p verifier --test rederive_differential rederive_differential_exact_agreement ) || {
    msg 1 "  differential.sh: the re-derivation differential DIVERGED (port vs in-tree engine)"
    exit 1
}
END=$(date +%s)
ELAPSED=$((END - START))
msg 2 "  differential.sh: differential green over ${N} programs (${ELAPSED}s)"
if [ "$ELAPSED" -gt "$BUDGET" ]; then
    msg 1 "  differential.sh: wall-clock budget exceeded (${ELAPSED}s > ${BUDGET}s, NFR-3) — review"
    exit 1
fi

# --- the automation-only proven build --------------------------------------
msg 3 "  differential.sh: automation-only proven build (proven_automation_only)"
( cd "$ROOT" && TYU_REDERIVE_E2E=1 \
    cargo test -q -p tooling-tests --test proven_automation_only ) || {
    msg 1 "  differential.sh: the automation-only proven build failed"
    exit 1
}
msg 2 "  differential.sh: automation-only proven build green (rederive discharges, no developer proofs)"

# --- the committed-corpus surface (always-on differential pin) -------------
msg 3 "  differential.sh: committed rederive corpus (byte-stable + coverage)"
( cd "$ROOT" && cargo test -q -p verifier --test rederive_differential committed_rederive_corpus_matches_regeneration ) || {
    msg 1 "  differential.sh: committed rederive corpus drifted from the generator"
    exit 1
}

msg 2 "  differential.sh: DIFFERENTIAL GATE GREEN (≥${N} programs exact agreement; automation-only proven; committed corpus stable)"