[package]
name = "codegen-riscv"
version = "0.1.0"
edition = "2021"
description = "RISC-V code generation backend for Tyu."

[dependencies]
frontend     = { path = "../frontend" }
ir           = { path = "../ir" }
semantics    = { path = "../semantics" }
codegen-core = { path = "../codegen-core" }
lmod         = { path = "../lmod" }
