import Tyu.Conformance.Json
import Tyu.Conformance.Parse
import Tyu.Gen.Render
import Tyu.Src
import Tyu.Step

/-! The fragment-vector conformance runner (PLAN-VERIFY-3 P9.3).

The pure-fragment *source* surface had no mechanical Lean↔Rust pin: each
side was internally drift-locked (Lean: the T-S theorems; Rust:
`cross_surface.rs` + the transcription-table test), but nothing pinned the
mnemonic↔op mapping AND the step semantics across the two languages. The
committed `tyu.fragvec/1` corpus closes it exactly the way the IR surface's
`tyu.vec/1` vectors did: a shared *program → trace* corpus.

The corpus is generated by `crates/verifier/tests/fragment_vectors.rs` as
canonical `--emit=ir` block text with expected observable traces (termination
+ exit stack), committed at `crates/verifier/test-vectors/fragment/index.json`.
This module parses the SAME text with this port's own parser
(`Tyu.Gen.Render.parseSrcBlocks` — the op-locality detector) and must
reproduce the committed traces byte-for-byte. A drift on either side — a
misparsed mnemonic, a wrong step (the `swap` bug this corpus caught first) —
diverges here and fails the port gate.

The observable equivalence class is deliberately narrow: termination and the
exit stack (memory is observed through the programs whose exit stack depends
on it — store→load replay, the load oracle, the MMIO oracle; the cell list
itself is not observable through either surface). -/

namespace Tyu.Conformance

open Tyu.Gen.Render (parseSrcBlocks)

/-- One `tyu.fragvec/1` program: canonical block text + metadata + the
committed expected trace. -/
structure FragVector where
  id : String
  blocks : String
  entry : Nat
  fuel : Nat
  stack : List Int
  localsCap : Nat
  loadOracle : Int
  mmioOracle : Int
  expectTerm : Bool
  expectStack : List Int
  deriving DecidableEq, Repr, Inhabited

/-- Extract one program from its JSON object (`none` on any malformed field —
the reader fails closed). -/
def fragFromJson (j : Json) : Option FragVector := do
  let id := (j.field "id").bind Json.asStr
  let blocks := (j.field "blocks").bind Json.asStr
  let entry := ((j.field "entry").bind Json.asInt |>.getD 0).toNat
  let fuel := ((j.field "fuel").bind Json.asInt |>.getD 0).toNat
  let localsCap := ((j.field "locals_cap").bind Json.asInt |>.getD 0).toNat
  let loadOracle := (j.field "load_oracle").bind Json.asInt |>.getD 0
  let mmioOracle := (j.field "mmio_oracle").bind Json.asInt |>.getD 0
  let stack := (j.field "stack").bind Json.asArr |>.getD []
  let expect := j.field "expect"
  let expectTerm := (expect.bind (fun e => (e.field "terminates").bind Json.asBool)).getD false
  let expectStack :=
    (expect.bind (fun e => (e.field "exit_stack").bind Json.asArr) |>.getD [])
  match id, blocks, stack.mapM Json.asInt, expectStack.mapM Json.asInt with
  | some id, some blocks, some stack, some expectStack => some {
      id := id, blocks := blocks, entry := entry, fuel := fuel,
      stack := stack, localsCap := localsCap, loadOracle := loadOracle,
      mmioOracle := mmioOracle, expectTerm := expectTerm, expectStack := expectStack }
  | _, _, _, _ => none

/-- The typed `tyu.fragvec/1` document. -/
structure FragFile where
  schema : String
  triple : String
  programs : List FragVector
  deriving DecidableEq, Repr, Inhabited

/-- Parse + schema-check a `tyu.fragvec/1` document. -/
def parseFragFile (input : String) : Option FragFile :=
  match parseJson input with
  | none => none
  | some j =>
      let schema := (j.field "schema").bind Json.asStr
      let triple := (j.field "triple").bind Json.asStr
      match schema, triple with
      | some s, some t =>
          if s ≠ "tyu.fragvec/1" then none
          else
            let ps := (j.field "programs").bind Json.asArr |>.getD []
            let parsed := ps.filterMap fragFromJson
            if parsed.length ≠ ps.length then none
            else some (FragFile.mk s t parsed)
      | _, _ => none

/-- One observed divergence (or a parse failure). -/
structure FragMismatch where
  id : String
  got : String
  want : String
  deriving DecidableEq, Repr

/-- The stack rendered as the corpus expects it (`[a,b]`, comma-separated). -/
def stackText (s : List Int) : String :=
  "[" ++ String.intercalate "," (s.map (fun v => toString v)) ++ "]"

/-- Run one program at the SOURCE surface (`Tyu.Src.Word.run` — the fragment
semantics; target `x86_64_unknown_none`, the corpus's authored triple; the
fragment data domain is target-transparent) and compare the observable trace
with the committed expectation. `none` = the program reproduced its
committed trace. -/
def runFragVector (v : FragVector) : Option FragMismatch :=
  match parseSrcBlocks v.blocks with
  | none => some { id := v.id, got := "unparseable-blocks", want := "fragment-blocks" }
  | some blocks =>
      let spec := Tyu.IR.x86_64_unknown_none
      let mem := Tyu.Step.ConcreteMem.empty (fun _ => v.loadOracle) (fun _ => v.mmioOracle)
      let st : Tyu.Step.State := { stack := v.stack, locals := List.replicate v.localsCap 0 }
      match Tyu.Src.Word.run blocks spec v.entry v.fuel mem st with
      | (_, some σf) =>
          if v.expectTerm && σf.stack == v.expectStack then none
          else some { id := v.id, got := stackText σf.stack, want := stackText v.expectStack }
      | (_, none) =>
          if v.expectTerm then
            some { id := v.id, got := "nonterminating", want := stackText v.expectStack }
          else none

/-- Run a whole fragment corpus file; returns the divergences. -/
def runFragFile (f : FragFile) : List FragMismatch :=
  f.programs.filterMap runFragVector

end Tyu.Conformance