//! Per-target interval-engine suites (PLAN-VERIFY-3 P2.2, "interval_targets").
//!
//! The reference semantics is a function of `(TargetSpec, MemModel)` (§Q3);
//! this suite holds the *width-relativism substrate* honest per target:
//!
//! - the width-domain functions (`word_domain`, `usize_max`) are correct for
//!   every recognized triple (32-bit and 64-bit branches);
//! - the MMIO nondeterministic read domain (§Q13) is width-bounded: a 32-bit
//!   target's unmodeled register read lives in `[-2^31, 2^31-1]` (ApertureMem
//!   default) while a 64-bit target's is `⊤`;
//! - the committed per-target vector corpus (`tyu.vec/1`, generated by
//!   `vector_corpus.rs`) is *data-transparent across the files themselves*:
//!   the exact artifact a port will consume has identical normative heads for
//!   the data-domain boundary classes on every triple.

use std::fs;
use std::path::PathBuf;

use verifier::interval::{usize_max, word_domain, Interval};
use verifier::mem::{ApertureMem, MemModel};
use verifier::target::{TargetSpec, TARGETS};

fn vec_index_path(triple: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("test-vectors")
        .join(triple)
        .join("index.json")
}

#[test]
fn word_domain_matches_each_target_width() {
    let cases: &[(TargetSpec, (i64, i64), u64)] = &[
        (
            TargetSpec::X86_64_UNKNOWN_LINUX_GNU,
            (i64::MIN, i64::MAX),
            i64::MAX as u64,
        ),
        (
            TargetSpec::X86_64_UNKNOWN_NONE,
            (i64::MIN, i64::MAX),
            i64::MAX as u64,
        ),
        (
            TargetSpec::ARM_V7M_UNKNOWN_NONE,
            (-(1i64 << 31), (1i64 << 31) - 1),
            (1u64 << 32) - 1,
        ),
        (
            TargetSpec::RISCV32_UNKNOWN_NONE,
            (-(1i64 << 31), (1i64 << 31) - 1),
            (1u64 << 32) - 1,
        ),
    ];
    for &(spec, (lo, hi), umax) in cases {
        assert_eq!(
            word_domain(spec.word_bits),
            (lo, hi),
            "word_domain for {} (word_bits {})",
            spec.triple,
            spec.word_bits
        );
        assert_eq!(
            usize_max(spec.word_bits),
            umax,
            "usize_max for {} (word_bits {})",
            spec.triple,
            spec.word_bits
        );
        assert_eq!(spec.signed_domain(), (lo, hi));
        assert_eq!(spec.usize_max(), umax);
    }
    // The width functions are pure: 64-bit == full i64; 32-bit bounds the
    // signed word; 0 (unset) means full i64.
    assert_eq!(word_domain(64), (i64::MIN, i64::MAX));
    assert_eq!(word_domain(0), (i64::MIN, i64::MAX));
    assert_ne!(word_domain(32), word_domain(64));
}

/// §Q13: an MMIO read yields a nondeterministic value within the register's
/// width. ApertureMem's default read is the target word domain; FlatMem stays
/// `⊤` (sound for any width — the pre-P2 behavior).
#[test]
fn mmio_read_domain_is_width_bounded() {
    // 32-bit target: unscripted 32-bit register read is the signed 32-bit
    // domain (never the full i64 — a 32-bit register cannot return 2^40).
    let mut mem32 = ApertureMem::new((0, 1 << 20));
    let read32 = mem32.aperture_read(&ir::Atom::new(b"r").unwrap(), 32);
    assert_eq!(
        read32,
        Interval::Range {
            lo: -(1i64 << 31),
            hi: (1i64 << 31) - 1
        }
    );

    // 64-bit target: the width-64 domain is the full i64 domain.
    let mut mem64 = ApertureMem::new((0, 1 << 20));
    let read64 = mem64.aperture_read(&ir::Atom::new(b"r").unwrap(), 64);
    assert_eq!(read64, Interval::TOP);

    // A scripted (refined) read wins over the nondeterministic domain —
    // the refinement seed of PLAN-VERIFY-3 §Q13 / P13.
    let mut mem = ApertureMem::new((0, 1 << 20));
    mem.script_read(&ir::Atom::new(b"r").unwrap(), Interval::const_val(7));
    let read = mem.aperture_read(&ir::Atom::new(b"r").unwrap(), 32);
    assert_eq!(read, Interval::const_val(7));
}

/// ApertureMem's RAM tracking is point-store-exact (the in-tree abstract
/// memory that later feeds the bundle conformance vectors).
#[test]
fn aperture_mem_tracks_point_stores_within_ram() {
    let mut mem = ApertureMem::new((0x1000, 0x2000));
    mem.store(Interval::const_val(0x1010), Interval::const_val(42));
    mem.store(Interval::const_val(0x1010), Interval::const_val(43)); // overwrite
    assert_eq!(
        mem.load(Interval::const_val(0x1010), 64),
        Interval::const_val(43)
    );

    // A different point in RAM was never written → ⊤ (garbage).
    assert_eq!(mem.load(Interval::const_val(0x1111), 64), Interval::TOP);
    // Outside RAM → ⊤.
    assert_eq!(mem.load(Interval::const_val(0x0), 64), Interval::TOP);
    // Non-point address → ⊤ (could alias anything).
    assert_eq!(
        mem.load(
            Interval::Range {
                lo: 0x1000,
                hi: 0x2000
            },
            64
        ),
        Interval::TOP
    );
    // Store to a non-point address is not tracked (sound ⊤ reads remain).
    mem.store(
        Interval::Range {
            lo: 0x1000,
            hi: 0x2000,
        },
        Interval::const_val(9),
    );
    assert_eq!(mem.load(Interval::const_val(0x1050), 64), Interval::TOP);
}

/// The committed vector corpora: the data-domain boundary classes are
/// byte-transparent across triples *in the artifact itself* (the file a port
/// will parse, not the in-memory generator). A 32-bit target's corpus keeps
/// the same normative heads as x86_64 — port vectors are portable because
/// the IR data domain is width-independent.
#[test]
fn committed_vectors_are_data_transparent_across_triples() {
    let reference = TargetSpec::X86_64_UNKNOWN_NONE;
    let mut ref_heads: Vec<(String, String)> = Vec::new();
    {
        let doc: serde_json::Value =
            serde_json::from_str(&fs::read_to_string(vec_index_path(reference.triple)).unwrap())
                .unwrap();
        for v in doc["vectors"].as_array().unwrap() {
            let id = v["id"].as_str().unwrap();
            // Data-domain transparency: compare the `flat` (FlatMem) classes
            // only — the `aperture` class is width-relative BY DESIGN (§Q13)
            // and is asserted separately by `vector_corpus`.
            if id.starts_with("boundary/") && v["model"].as_str().unwrap() == "flat" {
                ref_heads.push((
                    id.to_string(),
                    v["expect"]["head"].as_str().unwrap().to_string(),
                ));
            }
        }
    }
    assert!(
        ref_heads.len() >= 10,
        "reference flat boundary heads must exist"
    );

    for spec in TARGETS.iter().copied() {
        if spec == reference {
            continue;
        }
        let path = vec_index_path(spec.triple);
        let text = fs::read_to_string(&path).unwrap_or_else(|_| {
            panic!(
                "vector corpus for {} missing ({})",
                spec.triple,
                path.display()
            )
        });
        let doc: serde_json::Value = serde_json::from_str(&text).unwrap();
        assert_eq!(
            doc["schema"].as_str().unwrap(),
            "tyu.vec/1",
            "{}: vector schema tag (P2.2 schema version)",
            spec.triple
        );
        let mut heads: Vec<(String, String)> = Vec::new();
        for v in doc["vectors"].as_array().unwrap() {
            let id = v["id"].as_str().unwrap();
            if id.starts_with("boundary/") && v["model"].as_str().unwrap() == "flat" {
                heads.push((
                    id.to_string(),
                    v["expect"]["head"].as_str().unwrap().to_string(),
                ));
            }
        }
        assert_eq!(
            heads.len(),
            ref_heads.len(),
            "{}: flat boundary set drifted",
            spec.triple
        );
        for (a, b) in heads.iter().zip(ref_heads.iter()) {
            assert_eq!(
                a, b,
                "{}: data-domain head differs from {}",
                spec.triple, reference.triple
            );
        }
    }
}

/// Every recognized target carries slot_bytes/arch_tag parity with the
/// verifier's own boundary identity (a guard against accidental renumbering).
#[test]
fn target_identity_table_is_the_boundary() {
    assert_eq!(TARGETS.len(), 4);
    for spec in TARGETS.iter() {
        assert_eq!(
            spec.triple,
            verifier::target::for_triple(spec.triple)
                .expect("resolvable")
                .triple
        );
        // slot_bytes ↔ word_bits well-formedness (8-byte slots are 64-bit).
        assert!(
            (spec.word_bits > 32) == (spec.slot_bytes > 4),
            "{}",
            spec.triple
        );
    }
}
