//! The re-derivation differential (PLAN-VERIFY-3 P14.2, §Q11 item 5/FR-13):
//! the port's `rederive` exe re-runs the abstract interpreter `Tyu.Abs`
//! over programs generated by `verifier::gen` and must agree with the
//! in-tree engine EXACTLY — per-program tri (the trust class) AND interval
//! (the discharged value). Zero divergence on ≥ 10^5 programs per run is
//! the §11.5 acceptance criterion, gated by `ci/differential.sh`.
//!
//! The committed corpus (`crates/verifier/test-vectors/rederive/index.json`,
//! 256 deterministic programs) is the always-on surface: it is
//! byte-compared against regeneration and executed by the port (`rederive
//! --corpus`, env-gated) in the regular CI. The big run writes a generated
//! corpus to a temp dir and drives the exe over it — never committed (the
//! corpus is a build artifact, exactly like the generator's other outputs).
//!
//! Env: `TYU_REDERIVE_N` overrides the big-run size (default 100_000);
//! `TYU_REDERIVE_N=0` exercises just the committed corpus via the exe.

use std::fs;
use std::path::PathBuf;
use std::process::Command;

mod common;

use common::{abstract_verdict, interval_text, intervals_text, json_esc, tri_name, workspace_root};
use verifier::gen::{gen_program, MemDesc, Program, Rng};
use verifier::interval::{Interval, Tri};
use verifier::target::TargetSpec;

const REDERIVE_SCHEMA: &str = "tyu.vec/1";
const SW_SEED: u64 = 0x5eed_0000_0000_0001;
const COMMITTED_N: usize = 256;

/// Canonical op text of a program (block-less, exactly `parseOps`' input).
fn prog_ops_text(prog: &Program) -> String {
    // The generator's ops are the IR ops; `common::canonical_op_text` renders
    // them through `ir::write_word_ops`.
    let blocks = vec![prog.ops.clone()];
    let w = common::build_word(&blocks, prog.n_inputs(), 1);
    let mut buf = common::VecOut(Vec::new());
    ir::write_word_ops(&mut buf, &w);
    let text = String::from_utf8_lossy(&buf.0).to_string();
    let mut lines: Vec<&str> = Vec::new();
    for line in text.lines() {
        if line.starts_with("block ") {
            continue;
        }
        lines.push(line);
    }
    lines.join("\n")
}

/// The entry stack text of a program (its input domains).
fn prog_entries_text(prog: &Program) -> String {
    intervals_text(
        &prog
            .domains
            .iter()
            .map(|&(lo, hi)| Interval::Range { lo, hi })
            .collect::<Vec<_>>(),
    )
}

/// One vector of the corpus document. A memory-bearing program (modeled RAM
/// region + scripted MMIO reads) renders as `model: "bundle"` with the
/// `reads` payload (mirroring `ApertureMem.script_read`), so the port's
/// `MemModel.bundle` executes the same refined surface as the Rust
/// `ApertureMem` instance (§Q3/Q13/P2.1).
fn vector_json(idx: usize, prog: &Program, expect: (Tri, Interval)) -> String {
    let has_mem = prog.mem.ram.is_some() || !prog.mem.scripted.is_empty();
    let model = if has_mem { "bundle" } else { "flat" };
    let mut out = String::new();
    out.push_str("    {");
    out.push_str(&format!("\"id\": \"prog/{:06}\",", idx));
    out.push_str("\"class\": \"rederive\",");
    out.push_str("\"row\": \"add_i64\",");
    out.push_str(&format!("\"model\": \"{model}\","));
    out.push_str("\"mode\": \"linear\",");
    out.push_str(&format!("\"ops\": \"{}\",", json_esc(&prog_ops_text(prog))));
    out.push_str(&format!(
        "\"entry\": \"{}\",",
        json_esc(&prog_entries_text(prog))
    ));
    out.push_str(&format!(
        "\"target\": [{}, {}],",
        prog.target.0, prog.target.1
    ));
    let cs = if prog.cast_site { "true" } else { "false" };
    out.push_str(&format!("\"cast_site\": {},", cs));
    if !prog.mem.scripted.is_empty() {
        // The scripted register reads (`ApertureMem.script_read` seeds).
        let reads: Vec<String> = prog
            .mem
            .scripted
            .iter()
            .map(|(k, v)| {
                format!(
                    "{{\"place\": \"{}\", \"lo\": {}, \"hi\": {}}}",
                    String::from_utf8_lossy(k.as_bytes()),
                    v,
                    v
                )
            })
            .collect();
        out.push_str(&format!("\"reads\": [{}],", reads.join(", ")));
    }
    out.push_str(&format!(
        "\"expect\": {{\"head\": \"{}\", \"top\": \"{}\"}}",
        tri_name(expect.0),
        interval_text(expect.1)
    ));
    out.push('}');
    out
}

/// The `tyu.vec/1` document for a set of generated programs. The `ram`
/// header answers the bundle-model vectors' modeled RAM window (P12.2).
fn render_corpus(programs: &[Program]) -> String {
    let has_ram = programs.iter().any(|p| p.mem.ram.is_some());
    let mut c = String::new();
    c.push_str(&format!(
        "{{\n  \"schema\": \"{REDERIVE_SCHEMA}\",\n  \"triple\": \"{}\",\n  \"target\": {{\n    \"slot_bytes\": 8,\n    \"word_bits\": 64,\n    \"arch_tag\": 0\n  }}",
        TargetSpec::X86_64.triple
    ));
    if has_ram {
        c.push_str(",\n  \"ram\": [4096, 8192]");
    }
    c.push_str(",\n  \"vectors\": [\n");
    for (i, prog) in programs.iter().enumerate() {
        let comma = if i + 1 < programs.len() { "," } else { "" };
        let expect = abstract_verdict(prog);
        c.push_str(&vector_json(i, prog, expect));
        c.push_str(&format!("{comma}\n"));
    }
    c.push_str("  ]\n}");
    c
}

fn corpus_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("test-vectors")
        .join("rederive")
}

/// The port's `rederive` exe path.
fn rederive_exe() -> PathBuf {
    workspace_root().join("verification/ports/lean/.lake/build/bin/rederive")
}

fn have_rederive_exe() -> bool {
    rederive_exe().exists()
}

/// Run `rederive --corpus` over a corpus dir and return its RESULT line.
fn run_rederive_corpus(dir: &std::path::Path) -> (bool, String) {
    let out = Command::new(rederive_exe())
        .arg("--corpus")
        .arg(dir)
        .output()
        .expect("run rederive --corpus");
    let stdout = String::from_utf8_lossy(&out.stdout).to_string();
    let ok = out.status.success() && stdout.contains("divergences=0");
    let result_line = stdout
        .lines()
        .find(|l| l.starts_with("RESULT:"))
        .unwrap_or("")
        .to_string();
    (ok, result_line)
}

/// A deterministic set of `n` generated programs from a seed.
fn generate(seed: u64, n: usize, mem: bool) -> Vec<Program> {
    let mut rng = Rng::new(seed);
    let mut programs = Vec::with_capacity(n);
    for _ in 0..n {
        let n_inputs = 1 + (rng.below(3) as usize);
        let cast_final = rng.below(4) == 0;
        let desc = if mem && rng.below(3) == 0 {
            MemDesc::ram_and_dev_script(0x1000, 0x2000, 7)
        } else {
            MemDesc::flat()
        };
        programs.push(gen_program(
            &mut rng,
            TargetSpec::X86_64,
            &desc,
            n_inputs,
            cast_final,
        ));
    }
    programs
}

/// The always-on corpus surface: the committed file byte-matches
/// regeneration (the generator is deterministic) and covers every engine
/// surface the transfer table has: all three discharge classes, cast-site
/// programs (the `castNarrow` row — the P14 review found the seed yielded
/// zero cast sites, leaving the row differentially unexercised at
/// always-on cadence), and bundle-model programs (the RAM + scripted-read
/// memory paths).
#[test]
fn committed_rederive_corpus_matches_regeneration() {
    let programs = generate(SW_SEED, COMMITTED_N, true);
    let doc = render_corpus(&programs);
    let dir = corpus_dir();
    let path = dir.join("index.json");
    if std::env::var("TYU_REGEN_REDERIVE_CORPUS").is_ok() || !path.exists() {
        fs::create_dir_all(&dir).expect("create rederive corpus dir");
        fs::write(&path, &doc).expect("write rederive corpus");
        eprintln!("wrote {path:?} ({COMMITTED_N} programs)");
    } else {
        let committed = fs::read_to_string(&path).expect("committed rederive corpus present");
        assert_eq!(
            committed, doc,
            "rederive corpus drifted from the deterministic generator — regenerate + review"
        );
    }
    // Coverage: all three discharge classes, plus at least one cast-site and
    // one bundle-model program — a seed that misses a surface silently
    // narrows what the always-on pin can catch.
    let mut discharged = 0;
    let mut failing = 0;
    let mut open = 0;
    let mut cast_sites = 0;
    let mut bundles = 0;
    for p in &programs {
        if p.cast_site {
            cast_sites += 1;
        }
        if p.mem.ram.is_some() || !p.mem.scripted.is_empty() {
            bundles += 1;
        }
        match abstract_verdict(p).0 {
            Tri::DefTrue => discharged += 1,
            Tri::DefFalse => failing += 1,
            Tri::Top => open += 1,
        }
    }
    assert!(discharged > 0, "corpus produced no discharges");
    assert!(failing > 0, "corpus produced no provably-failing");
    assert!(open > 0, "corpus produced no open verdicts");
    assert!(cast_sites > 0, "corpus produced no cast-site programs");
    assert!(bundles > 0, "corpus produced no bundle-model programs");
}

/// The differential (env-gated): ≥ `TYU_REDERIVE_N` generated programs run by
/// BOTH engines — the Rust generator+discharge writes the expectations and
/// the port's `rederive --corpus` re-derives them. Exact agreement (tri AND
/// interval) is the §11.5 criterion. Runs unconditionally over the committed
/// corpus when the exe is present; the big run is forced by
/// `ci/differential.sh` (`TYU_REDERIVE_E2E=1`).
#[test]
fn rederive_differential_exact_agreement() {
    let e2e = std::env::var("TYU_REDERIVE_E2E").is_ok();
    let default_n = if e2e { 100_000 } else { COMMITTED_N };
    let n: usize = match std::env::var("TYU_REDERIVE_N") {
        Ok(s) => s.parse::<usize>().unwrap_or(default_n),
        Err(_) => default_n,
    };
    let seed = if e2e { 0x0d15_a5e0_d15a_5e0d } else { SW_SEED };
    let with_mem = e2e;

    let programs = generate(seed, n, with_mem);
    let doc = render_corpus(&programs);

    if !e2e && !have_rederive_exe() {
        // Regular `cargo test` without the toolchain: the committed corpus
        // still self-checks (expectation stability).
        let path = corpus_dir().join("index.json");
        let committed = fs::read_to_string(&path).expect("committed corpus present");
        assert_eq!(
            committed, doc,
            "corpus drift from the deterministic generator"
        );
        eprintln!("rederive exe absent — committed-corpus self-check only");
        return;
    }

    let tmp = std::env::temp_dir().join(format!("tyu-rederive-{seed:x}-{n}"));
    fs::create_dir_all(&tmp).expect("temp corpus dir");
    fs::write(tmp.join("index.json"), &doc).expect("write corpus");
    // Generator determinism: re-render byte-identically.
    assert_eq!(doc, render_corpus(&programs), "generator nondeterminism");

    if !have_rederive_exe() {
        panic!("TYU_REDERIVE_E2E requires the Lean port (ci/differential.sh builds it)");
    }
    let (ok, line) = run_rederive_corpus(&tmp);
    let _ = fs::remove_dir_all(&tmp);
    assert!(
        ok,
        "rederive differential DIVERGED over {n} programs; result: {line}\n\
         the port's abstract re-run must agree with the in-tree engine on every \
         obligation (tri = trust class, interval = value)"
    );
}
