[package]
name = "langc"
version = "0.1.0"
edition = "2021"

[lib]
name = "langc"
path = "src/lib.rs"

[[bin]]
name = "langc"
path = "src/main.rs"
test = false

[dependencies]
hosted = { path = "../hosted" }
hosted-rt = { path = "../hosted-rt" }
frontend = { path = "../frontend" }
semantics = { path = "../semantics" }
ir = { path = "../ir" }
codegen-core  = { path = "../codegen-core" }
codegen-x86_64 = { path = "../codegen-x86_64" }
codegen-arm   = { path = "../codegen-arm" }
codegen-riscv = { path = "../codegen-riscv" }
lmod           = { path = "../lmod" }

[dev-dependencies]
